[package]
name = "ezytutors"
version = "0.1.0"
authors = ["claudioed <claudioed.oliveira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = ["tutor-nodb"]